name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:

jobs:
  generate:
    name: Generate Snake
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Generate the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          # github user name
          # using action context var ensures it's correct
          github_user_name: ${{ github.repository_owner }}

          # path of the generated gif
          # If you want it as SVG, change it to `output/github-snake.svg`
          outputs: dist/github-snake.svg

      # Push the generated snake.svg to the output branch
      # The output branch is named "output" and will be created automatically
      - name: Push Snake Animation to Output Branch
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist

